name: Production Tag Deployment
env:
  NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
on:
  push:
    tags:
      - 'prod-v*'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create .env
        shell: bash
        run: |
          echo "${{ secrets.PROD_ENV }}" >> .env

      - name: Build
        run: npm run build

      - name: Deploy Project Artifacts to Netlify
        run: npx netlify deploy --prod --site=${{ secrets.PROD_NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=dist
