name: apple-fe-ci

on:
  pull_request:
    branches:
      - "main"

permissions: write-all

jobs:
  compile-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
